version: '2.0'
services:
  frontend:
    image: ttt_front
    build:
      context: frontend
      dockerfile: Dockerfile
      args:
        - IP=${IP}
        - API_GATEWAY_URL=${API_GATEWAY_URL}
    ports:
      - 8081:3000
  backend:
    image: ttt_back
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - USER_POOL_ID=${USER_POOL_ID}
      - APP_CLIENT_ID=${APP_CLIENT_ID}
      - COGNITO_REGION=${COGNITO_REGION}
      - S3_REGION=${S3_REGION}
      - S3_PROFILE_PICTURES=${S3_PROFILE_PICTURES}
      - SNS_TOPIC_ARN=${SNS_TOPIC_ARN}
